# Generated by Django 4.2.19 on 2025-02-27 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praksis_nhn_nautobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samband',
            options={'ordering': ['name'], 'verbose_name': '', 'verbose_name_plural': 's'},
        ),
        migrations.RemoveField(
            model_name='samband',
            name='description',
        ),
        migrations.AddField(
            model_name='samband',
            name='actually_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='bandwidth_down',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='samband',
            name='bandwidth_string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='bandwidth_up',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='samband',
            name='_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='cost_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='cost_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='dekningsbidrag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='dekningsgrad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='desired_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='details_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samband',
            name='express_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='initial_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='install_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='live_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='location_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='order_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='praksis_nhn_nautobot.samband'),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_a_address_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_a_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_a_geo_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_a_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_a_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_b_address_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_b_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_b_geo_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_b_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='pop_b_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='sambandsnummer',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='smbnr_nhn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='smbnr_orig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='smbnr_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='start_invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='termination_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='termination_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='transporttype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='transporttype_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='samband',
            name='vendor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
