# Generated by Django 4.2.19 on 2025-03-25 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("praksis_nhn_nautobot", "0003_alter_samband_options_remove_samband__url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samband",
            name="bandwidth_string",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="samband",
            name="location",
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="samband",
            name="location_type",
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="samband",
            name="name_prefix",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_a_address_string",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_a_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_a_geo_string",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_a_room",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_b_address_string",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_b_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_b_geo_string",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="pop_b_room",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="sambandsnummer",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="samband",
            name="smbnr_nhn",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="samband",
            name="smbnr_prefix",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="samband",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="transporttype",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="samband",
            name="vendor",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
