# Generated by Django 4.2.19 on 2025-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("praksis_nhn_nautobot", "0004_alter_samband_bandwidth_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samband",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
